# convert below to docker-compose
# docker run --name workflow-redis -d redis redis-server --save 60 1 --loglevel warning
# docker run --name workflow-postgres -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" -p 5432:5432 -d postgres
services:
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - workflow
  postgres:
    image: postgres
    env_file: .envdocker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: postgres
    networks:
      - workflow
  engine:
    build: .
    env_file: .envdocker
    depends_on:
      - redis
      - postgres
    networks:
      - workflow

networks:
  workflow:
    driver: bridge